import {
    mdiAccountVoice,
    mdiChevronUp,
    mdiChevronDown,
    mdiGiftOpenOutline,
    mdiMenu,
    mdiPhoneOutline,
    mdiTabletCellphone,
    mdiLaptop,
    mdiTelevision,
    mdiCctv,
    mdiBank,
    mdiMicrophoneMessage,
    mdiCreditCardFastOutline,
    mdiTruckDeliveryOutline,
    mdiAccountConvert,
    mdiFileArrowLeftRight,
    mdiClockFast,
    mdiChartTimelineVariantShimmer,
    mdiChevronRight,
    mdiMessageReplyTextOutline,
    mdiFacebookMessenger,
    mdiInstagram,
    mdiWhatsapp,
    mdiWindowClose,
    mdiTrayArrowUp,
    mdiDelete,
    mdiLink
} from '@mdi/js'

export default {
    gift: mdiGiftOpenOutline,
    accountVoice: mdiAccountVoice,
    phone: mdiPhoneOutline,
    TheMenu: mdiMenu,
    arrowDown: mdiChevronDown,
    arrowUp: mdiChevronUp,
    tabletPhone: mdiTabletCellphone,
    laptop: mdiLaptop,
    television: mdiTelevision,
    securityCamera: mdiCctv,
    bank: mdiBank,
    microphone: mdiMicrophoneMessage,
    card: mdiCreditCardFastOutline,
    truck: mdiTruckDeliveryOutline,
    changeUser: mdiAccountConvert,
    changeFile: mdiFileArrowLeftRight,
    clockFast: mdiClockFast,
    statistic: mdiChartTimelineVariantShimmer,
    arrowRight: mdiChevronRight,
    message: mdiMessageReplyTextOutline,
    messenger: mdiFacebookMessenger,
    instagram: mdiInstagram,
    whatsapp: mdiWhatsapp,
    close: mdiWindowClose,
    upload: mdiTrayArrowUp,
    delete: mdiDelete,
    link: mdiLink
}
